/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness and dependency check
     * @description Returns build information and the reachability of each dependency. Always 200 so a load balancer can distinguish "process is up" from "database is down" by reading the body. Unauthenticated, because a probe has no credentials.
     */
    get: operations['HealthController_check_v1'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register an agency and its first administrator
     * @description Creates the tenant and its `agency_admin` in one transaction and returns a session. The tenant starts as `pending` until an administrator vets it.
     */
    post: operations['AuthController_register_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Exchange credentials for a token pair
     * @description Returns the same message whether the address is unknown or the password is wrong, so the response cannot be used to discover which addresses are registered.
     */
    post: operations['AuthController_login_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rotate a refresh token
     * @description Refresh tokens are single-use. Presenting one that has already been rotated revokes every token in its family, because a replay and a stolen token are indistinguishable.
     */
    post: operations['AuthController_refresh_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * End the session behind a refresh token
     * @description Idempotent: an unknown token succeeds rather than reporting whether it existed.
     */
    post: operations['AuthController_logout_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** The identity behind the current access token */
    post: operations['AuthController_me_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/onboarding-links': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Issue a student invitation link
     * @description The URL is returned once and never again — only a hash is stored. The tenant comes from your token, not from the request body.
     */
    post: operations['OnboardingLinksController_issue_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/onboarding-links/consume': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Redeem an invitation link
     * @description Public, because the student has no account yet. Expired, revoked, already-used and unknown tokens all return the same message.
     */
    post: operations['OnboardingLinksController_consume_v1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/onboarding-links/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke an invitation link */
    delete: operations['OnboardingLinksController_revoke_v1'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthDependenciesDto: {
      /**
       * @description Postgres reachability.
       * @enum {string}
       */
      database: 'up' | 'down';
    };
    HealthResponseDto: {
      /** @example ok */
      status: string;
      /** @enum {string} */
      environment: 'development' | 'test' | 'production';
      /**
       * @description Commit the running build came from.
       * @example a1b2c3d
       */
      version: string;
      /** @example 42 */
      uptimeSeconds: number;
      dependencies: components['schemas']['HealthDependenciesDto'];
    };
    RegisterAgencyDto: {
      /**
       * @description Agency name.
       * @example Northwind Education
       */
      agencyName: string;
      /**
       * @description Subdomain label. Lowercase letters, digits and hyphens.
       * @example northwind
       */
      slug: string;
      /** @example ada@northwind.example */
      email: string;
      /** @example Ada Lovelace */
      fullName: string;
      /** @example correct-horse-battery */
      password: string;
    };
    /** @enum {string} */
    Role: 'platform_admin' | 'agency_admin' | 'counselor' | 'institution_user' | 'student';
    AuthUserDto: {
      /** Format: uuid */
      id: string;
      /** @example ada@northwind.example */
      email: string;
      /** @example Ada Lovelace */
      fullName: string;
      role: components['schemas']['Role'];
      /**
       * Format: uuid
       * @description Null for a platform administrator.
       */
      tenantId: string | null;
    };
    AuthTokensDto: {
      /** @description Short-lived JWT. Send as `Authorization: Bearer <token>`. */
      accessToken: string;
      /** @description Opaque, single-use. Rotated on every refresh. */
      refreshToken: string;
      /**
       * @description Access token lifetime in seconds.
       * @example 900
       */
      expiresIn: number;
      user: components['schemas']['AuthUserDto'];
    };
    LoginDto: {
      /** @example ada@northwind.example */
      email: string;
      /** @example correct-horse-battery */
      password: string;
    };
    RefreshDto: {
      /** @description The refresh token from the previous login or refresh. */
      refreshToken: string;
    };
    IssueOnboardingLinkDto: {
      /**
       * @description Who the invitation is for.
       * @example student@example.com
       */
      inviteeEmail: string;
      /**
       * @description Days until the link expires. Defaults to 14.
       * @example 14
       */
      expiresInDays?: number;
    };
    OnboardingLinkDto: {
      /** Format: uuid */
      id: string;
      /** @description The full invitation URL. Shown once, at issue time — only a hash is stored, so it cannot be retrieved again. */
      url: string;
      /** @example student@example.com */
      inviteeEmail: string;
      /** Format: date-time */
      expiresAt: string;
    };
    ConsumeOnboardingLinkDto: {
      /** @description The token from the invitation link. */
      token: string;
    };
    ConsumedLinkDto: {
      /** Format: uuid */
      tenantId: string;
      /** @example student@example.com */
      inviteeEmail: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_check_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
    };
  };
  AuthController_register_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterAgencyDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthTokensDto'];
        };
      };
      /** @description The subdomain is already taken. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthTokensDto'];
        };
      };
      /** @description Credentials are not valid, or the account is inactive. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refresh_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthTokensDto'];
        };
      };
      /** @description Token unknown, expired, or already used. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_logout_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshDto'];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_me_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The authenticated user. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing, invalid or expired bearer token. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OnboardingLinksController_issue_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['IssueOnboardingLinkDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OnboardingLinkDto'];
        };
      };
      /** @description Only an agency admin or counselor may issue links. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OnboardingLinksController_consume_v1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConsumeOnboardingLinkDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConsumedLinkDto'];
        };
      };
      /** @description The link is not valid. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OnboardingLinksController_revoke_v1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
